name: Move new issues into Triage

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: hayuna/github-project-automation-plus@v0.1.0
        with:
          project: Backlog
          column: Todo
          repo-token: ${{ secrets.GITHUB_TOKEN }}

